apiVersion: v1
kind: ServiceAccount
metadata:
  name: aster-backend
  namespace: aster-staging
  labels:
    app: aster-backend
    environment: staging
    managed-by: terraform
  annotations:
    iam.gke.io/gcp-service-account: aster-staging-backend@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aster-frontend
  namespace: aster-staging
  labels:
    app: aster-frontend
    environment: staging
    managed-by: terraform
  annotations:
    iam.gke.io/gcp-service-account: aster-staging-frontend@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: aster-staging
  name: aster-backend-role
  labels:
    app: aster-backend
    environment: staging
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aster-backend-binding
  namespace: aster-staging
  labels:
    app: aster-backend
    environment: staging
subjects:
- kind: ServiceAccount
  name: aster-backend
  namespace: aster-staging
roleRef:
  kind: Role
  name: aster-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: aster-staging
  name: aster-frontend-role
  labels:
    app: aster-frontend
    environment: staging
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aster-frontend-binding
  namespace: aster-staging
  labels:
    app: aster-frontend
    environment: staging
subjects:
- kind: ServiceAccount
  name: aster-frontend
  namespace: aster-staging
roleRef:
  kind: Role
  name: aster-frontend-role
  apiGroup: rbac.authorization.k8s.io
---
# Cluster-level permissions for monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aster-monitoring-reader
  labels:
    environment: staging
    purpose: monitoring
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aster-monitoring-binding
  labels:
    environment: staging
    purpose: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aster-monitoring-reader
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: monitoring