# Development Profile (Devcontainer)
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:172.17.0.1}:${DB_PORT:5433}/astarmanagement_dev
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  
  jpa:
    show-sql: true
  
  flyway:
    baseline-on-migrate: true
  
  # Redis Configuration for Devcontainer
  data:
    redis:
      host: ${REDIS_HOST:host.docker.internal}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      connect-timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
  
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "Astarmanagement:"
  
  # Disable Docker Compose integration
  docker:
    compose:
      enabled: false

# JWT Configuration for Development
app:
  jwt:
    expiration: 7200
    refresh-expiration: 172800
    issuer: Astarmanagement-dev-api

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG