# Astar Management Application Configuration
# Common settings shared across all profiles
spring:
  application:
    name: AstarManagement
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  # Common Database Configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false  # Critical: Must match Hibernate's provider_disables_autocommit setting
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 2
      validation-timeout: 5000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Performance Optimization
        jdbc:
          batch_size: 25
          batch_versioned_data: true
          fetch_size: 100
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
        connection:
          provider_disables_autocommit: true
        generate_statistics: true
        # Auditing
        envers:
          audit_table_suffix: _audit
          revision_field_name: rev
          revision_type_field_name: revtype
    show-sql: false
  
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
    out-of-order: true
  
  # Cache Configuration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5m
    cache-names: jwks
  
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${auth0.domain}/
          jwk-set-uri: https://${auth0.domain}/.well-known/jwks.json

# Server Configuration
server:
  port: 8080

# Auth0 Configuration
auth0:
  domain: ${AUTH0_DOMAIN:}
  audience: ${AUTH0_AUDIENCE:}

# OpenAPI Configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    persist-authorization: true
  packages-to-scan: com.astarworks.astarmanagement.core
  default-produces-media-type: application/json

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      jwks-endpoint:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 90
        slow-call-duration-threshold: 2s
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true

# Logging Configuration
logging:
  level:
    com.astarworks.astarmanagement: INFO
    org.flywaydb: WARN
    org.springframework.jdbc: WARN
    org.springframework.security: INFO